services:
  - type: web
    name: ipo-pilot
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: GIN_MODE
        value: release
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
